Running masm natively
istareatscreens/vscode-masm-runner pull request #2
Opened 2022-07-23 07:36 UTC by letmegro

With this code I have been able to link the files and have masm run natively in the vscode terminal
currently in this version of the feature the code will only run in powershell.

2022-07-23 21:15 UTC, istareatscreens requested changes

2022-07-24 04:02 UTC, letmegro commented on extension/src/extension.ts
> +  const IRVINE32_PATH = vscode.Uri.joinPath(
you mean like have a function create the joinpath and return it?

2022-07-24 04:03 UTC, letmegro commented on extension/src/extension.ts
> +  let path_link: string = __dirname.slice(0, __dirname.lastIndexOf("\\"));
got it

2022-07-24 04:04 UTC, letmegro commented on extension/src/extension.ts
> +  fs.writeFile(new_path.fsPath, file_data, (error) => {
that's doable

2022-07-24 05:04 UTC, letmegro commented on extension/src/extension.ts
> +      temp_file.fileName.slice(-3)
would tell the user a lot more if that was the case

2022-07-24 05:16 UTC, letmegro commented on extension/src/extension.ts
> +  //note: possibly have it instead of creating a new file replace it in the same file and change it back afterwards
it is not touching the user file it is touching the temp file which was created hence the new_path variable
is that still an issue?

2022-07-24 05:34 UTC, istareatscreens commented on extension/src/extension.ts
> +  const IRVINE32_PATH = vscode.Uri.joinPath(
You use closure to add the base path to the joinPath function then you just pass an array of directories and a file to the function the main function returns

2022-07-24 05:35 UTC, istareatscreens commented on extension/src/extension.ts
> +  //note: possibly have it instead of creating a new file replace it in the same file and change it back afterwards
I was replying to your comment on line 214

2022-07-27 07:34 UTC, closed without merging